# Generated by Django 6.0.3 on 2026-03-11 08:39

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/profile_photo.png', null=True, upload_to='avatars/', validators=[content.validators.validate_image_size]),
        ),
    ]
