# Generated by Django 6.0.3 on 2026-03-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='game_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='has_game_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='has_loader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='has_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='content.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='content.theme'),
        ),
    ]
