# Generated by Django 6.0.3 on 2026-03-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_game_version_contenttype_has_game_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='content.category'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='content.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_game_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_loader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
