# Generated by Django 6.0.3 on 2026-03-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_content_type_alter_theme_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content_type',
            new_name='category',
        ),
    ]
