# Generated by Django 6.0.3 on 2026-03-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_content_type_content_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='content_type',
            new_name='category',
        ),
    ]
