# Generated by Django 6.0.3 on 2026-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_content_type_theme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='discord_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='issues_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='source_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='wiki_link',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
