# Generated by Django 6.0.3 on 2026-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_discord_link_content_issues_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/item_icon.png', null=True, upload_to='thumbnails/'),
        ),
    ]
