# Generated by Django 6.0.3 on 2026-03-11 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_theme_category_alter_content_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentversion',
            name='loader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='content.loader'),
        ),
        migrations.AddField(
            model_name='contentversion',
            name='loader_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
