# Generated by Django 6.0.3 on 2026-03-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contentversion_loader_contentversion_loader_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
