# Generated by Django 6.0.3 on 2026-03-11 08:39

import content.models
import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_content_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/item_icon.png', null=True, upload_to='thumbnails/', validators=[content.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='file',
            field=models.FileField(upload_to=content.models.version_file_path, validators=[content.validators.validate_content_file_size]),
        ),
    ]
