# Generated by Django 6.0.3 on 2026-03-16 06:37

import content.models
import content.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_content_author_alter_content_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentversion',
            name='file',
            field=models.FileField(upload_to=content.models.version_file_path, validators=[content.validators.validate_content_file_size, content.validators.validate_zip_file]),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('malware', 'Malware or harmful file'), ('inappropriate', 'Inappropriate content'), ('stolen', 'Stolen content'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.content')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('content', 'reporter')},
            },
        ),
    ]
