# Generated by Django 6.0.3 on 2026-04-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_sitemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='game_version',
        ),
    ]
