# Generated by Django 6.0.3 on 2026-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_content_game_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='ai_used',
            field=models.BooleanField(default=True),
        ),
    ]
