# Generated by Django 6.0.3 on 2026-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_content_ai_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ai_used',
            field=models.CharField(choices=[('none', 'No AI used'), ('assisted', 'AI helped with this'), ('generated', 'I vibecoded this')], default='none', max_length=20),
        ),
    ]
