# Generated by Django 6.0.3 on 2026-04-09 05:45

from django.db import migrations

def fix_ai_used(apps, schema_editor):
    Content = apps.get_model('content', 'Content')
    Content.objects.all().update(ai_used='none')

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_content_ai_used'),
    ]

    operations = [
        migrations.RunPython(fix_ai_used, migrations.RunPython.noop),
    ]
